version: '3'
services:
  spotiplay-client:
    container_name: spotiplay-client
    build: 
     context: .
     dockerfile: Dockerfile
    image: spotiplay-client:latest
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
