version: '3.8'

services:
  spotiplay-web:
    container_name: spotiplay-web
    image: tubes-1:latest
    hostname: spotiplay-web
    env_file:
      - .env
    ports:
      - "8000:80" 
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini

  spotiplay-server:
    container_name: spotiplay-server
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5434:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  postgres-data:
